<a href="https://colab.research.google.com/github/sabbirpuspo/smart-grid-stability-ml-benchmark/blob/main/smart_grid_stability_ml_benchmark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ============================================================
# Project: Smart Grid Stability Prediction
# Purpose: Machine Learning Benchmark
# Dataset: Electrical Grid Stability Simulated Data
# Environment: Google Colab
# ============================================================

import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

print("Python version:", sys.version)
print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)
print("Scikit-learn version:", sklearn.__version__)

print("\nProject environment initialized successfully.")

Python version: 3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]
NumPy version: 2.1.3
Pandas version: 2.2.3
Scikit-learn version: 1.6.1

Project environment initialized successfully.

In [2]:
# ============================================================
# Step 1: Mount Google Drive
# ============================================================

from google.colab import drive

drive.mount('/content/drive')

print("Google Drive connected successfully.")

Mounted at /content/drive
Google Drive connected successfully.

In [6]:
# ============================================================
# Step 2: Locate the dataset
# ============================================================

import os

dataset_folder = "/content/drive/MyDrive/Smart Grid Stability Dataset"

print("Files in the dataset folder:")

for filename in os.listdir(dataset_folder):
    print(filename)

Files in the dataset folder:
smart_grid_stability_augmented.csv

In [7]:
# ============================================================
# Step 3: Load the smart-grid dataset
# ============================================================

import pandas as pd

file_path = os.path.join(
    dataset_folder,
    "smart_grid_stability_augmented.csv"
)

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Number of samples:", df.shape[0])
print("Number of columns:", df.shape[1])

Dataset loaded successfully!
Number of samples: 60000
Number of columns: 14

In [8]:
df.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable

In [9]:
print(df.columns.tolist())

['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2', 'g3', 'g4', 'stab', 'stabf']

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tau1    60000 non-null  float64
 1   tau2    60000 non-null  float64
 2   tau3    60000 non-null  float64
 3   tau4    60000 non-null  float64
 4   p1      60000 non-null  float64
 5   p2      60000 non-null  float64
 6   p3      60000 non-null  float64
 7   p4      60000 non-null  float64
 8   g1      60000 non-null  float64
 9   g2      60000 non-null  float64
 10  g3      60000 non-null  float64
 11  g4      60000 non-null  float64
 12  stab    60000 non-null  float64
 13  stabf   60000 non-null  object
dtypes: float64(13), object(1)
memory usage: 6.4+ MB

In [11]:
df["stabf"].value_counts()

stabf
unstable    38280
stable      21720
Name: count, dtype: int64